#!/bin/bash
# Copyright (c) 2012 Niki Kovacs <info@microlinux.fr>
# -----------------------------------------------------------------------------
#
# · This script builds all Slackware packages listed in the 'build_order' file. 
#
# · It puts them in the '$OUTPUT' directory. 
#
# · If the package already exists in '$OUTPUT' AND if it's already
#   installed, the script skips to the next package.
#
# · Otherwise it builds and installs the package, until all packages listed in
#   the 'build_order' file are built.
#

CWD=`pwd`
SOURCEDIR=$CWD
case $(uname -m) in 
  x86_64) OUTPUT=$CWD/../desktop-kde-14.1-64bit/slackware64 ;;
  *     ) OUTPUT=$CWD/../desktop-kde-14.1-32bit/slackware ;;
esac	
export OUTPUT

# Set the number of parallel make jobs
NUMJOBS="-j5"
export NUMJOBS="$NUMJOBS"

PACKAGES=$(egrep -v '(^\#)|(^\s+$)' $CWD/build_order)

for PACKAGE in $PACKAGES; do
	if [ -r ${OUTPUT}/${PACKAGE}-[r,0-9]*.txz ] ; then
		if [ -r /var/log/packages/${PACKAGE}-[r,0-9]* ] ; then
			continue
		fi
	fi
	echo
	echo "+=============================================================================="
	echo "| Building package ${PACKAGE}..."
	echo "+=============================================================================="
	echo 
	sleep 3

	(
		cd ${SOURCEDIR}/${PACKAGE} || exit 1
		./${PACKAGE}.SlackBuild || exit 1
	)
	upgradepkg --install-new ${OUTPUT}/${PACKAGE}-[r,0-9]*.txz || exit 1
done

echo 
echo "+=============================================================================="
echo "| Successfully built and installed all packages !"
echo "+=============================================================================="
echo

